GET  http://127.0.0.1:8081/api/slots/?turf_id=3&date=2026-01-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NzM2MjYwLCJpYXQiOjE3Njc3MzUzNjAsImp0aSI6IjBlZmYwYTllNjUwMzQ5NGJiZTlkMjE5N2Y2YTNmZjg0IiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.Tb10NV9V-e1Q655cH3eMhIJOiUR3vznOKA-Fdtf2Wes
Content-Type: application/json



###
POST http://localhost:8081//api/slots/bulk-save/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3ODg1NDUyLCJpYXQiOjE3Njc4ODQ1NTIsImp0aSI6IjM5ZmQ3M2VkZTBkMTQyMmQ5Yzg5MmNjZjVhOGFhNDhlIiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.vicpgzxmEuUyM2XTvWUKXS802ekULWjYb2PzzgNU1mg

{
  "turf_id": 8,
  "date": "2026-01-18",
  "slots": [
    {
      "from": "06:00 AM",
      "to": "10:00 AM",
      "status": "AVAILABLE",
      "price": 2000,
      "label": "Weekend Block"
    },
    {
      "from": "10:00 AM",
      "to": "02:00 PM",
      "status": "AVAILABLE",
      "price": 2000,
      "label": "Weekend Block"
    }
  ]
}




###
POST http://localhost:8081//api/slots/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NzM2ODM1LCJpYXQiOjE3Njc3MzU5MzUsImp0aSI6IjMzZjRhZGQxZGFjODRlMDE4YTVkNDlkZDA4NTIwNjEyIiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.08HK7E_AIKydyPvge8lHrfnsmSRKDN9_V9rMb9hEHYE


{
  "turf": 2,
  "date": "2026-01-07",
  "start_time": "06:00:00",
  "end_time": "07:00:00",
  "status": "AVAILABLE",
  "price": "40.00",
  "label": "Open Session"
}


###
PATCH http://localhost:8081//api/slots/19/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NzM2ODM1LCJpYXQiOjE3Njc3MzU5MzUsImp0aSI6IjMzZjRhZGQxZGFjODRlMDE4YTVkNDlkZDA4NTIwNjEyIiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.08HK7E_AIKydyPvge8lHrfnsmSRKDN9_V9rMb9hEHYE

{
  "status": "MAINTENANCE",
  "price": "0.00",
  "label": "Field Maintenance"
}

###
GET http://192.168.1.47:8081/api/list/turfs/
Content-Type: application/json


###
PATCH  http://localhost:8081/api/slots/smart-save/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3NzkzMDk0LCJpYXQiOjE3Njc3OTIxOTQsImp0aSI6IjgyYzMwMDY3ZDg0MzRkNTU5MDFmZWM1NDQyNjgwNDk4IiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.fS6-WwYAwZ6wCIHUuiea4m2FvD1bCa4qzvyr8kN9McU

{
  "turf_id": 7,
  "date": "2026-01-08",
  "slots": [
    {
      "from": "08:00 AM",
      "to": "09:00 AM",
      "status": "AVAILABLE",
      "price": "1500",
      "label": "Open Session"
    },
    {
      "from": "09:00 AM",
      "to": "10:00 AM",
      "status": "MAINTAINANCE",
      "price": "0",
      "label": "Admin Block"
    },
    {
      "from": "11:00 AM",
      "to": "12:00 AM",
      "status": "BOOKED",
      "price": "0",
      "label": "Admin Block"
    },
    {
      "from": "19:00 PM",
      "to": "20:00 PM",
      "status": "BLOCKED",
      "price": "0",
      "label": "Admin Block"
    }
  ]
}

####
POST http://localhost:9000/api/booking/slot/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3ODEwNDEyLCJpYXQiOjE3Njc4MDk1MTIsImp0aSI6IjgzYTFiYTZkM2UwNjQ1ZjVhMzk2ZDg4OGZmOGY5MGU5IiwidXNlcl9pZCI6IjYiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6InZlbmthdEBnbWFpbC5jb20ifQ.vr6qEdJ2YKVNQKvV7AeJQOI-xTnVOJyIjDiKgAu0eqY


{
  "turf_data": {
    "turf_id": "1"
  },
  "booking_details": {
    "booking_date": "2026-01-08",
    "sport": "Football"
  },
  "slots_booked": [
    {
      "slot_id": 0,
      "from_time": "04:00 PM",
      "to_time": "05:00 PM",
      "status": "PENDING",
      "price": "50.00",
      "label": "Standard Booking"
    },
    {
      "slot_id": 0,
      "from_time": "05:00 PM",
      "to_time": "06:00 PM",
      "status": "PENDING",
      "price": "50.00",
      "label": "Standard Booking"
    }
  ],
  "price_breakdown": {
    "total_amount": 105.00
  },
  "user_details": {
    "user_id": 6
  }
}

###
GET http://localhost:8081/api/bookings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3ODc1Mzg2LCJpYXQiOjE3Njc4NzQ0ODYsImp0aSI6IjA3NmM1OGY4YmM1ZjRlOWE4YWQyODllN2FmN2JlMDBlIiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.dgixb7RzWWdJb389c9H5hbfNGVeZ2rhr9-XDs3bapXc



###
GET http://localhost:8081/api/bookings/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3ODc1Mzg2LCJpYXQiOjE3Njc4NzQ0ODYsImp0aSI6IjA3NmM1OGY4YmM1ZjRlOWE4YWQyODllN2FmN2JlMDBlIiwidXNlcl9pZCI6IjEwIiwicm9sZSI6ImJ1c2luZXNzIiwiZW1haWwiOiJqYW5pQGdtYWlsLmNvbSJ9.dgixb7RzWWdJb389c9H5hbfNGVeZ2rhr9-XDs3bapXc