# Generated by Django 6.0 on 2026-01-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turf', '0004_maintenanceblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Maintenance'), ('BLOCKED', 'Blocked'), ('TOURNAMENT', 'Tournament')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Turf.turf')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('turf', 'date', 'start_time')},
            },
        ),
    ]
