# Generated by Django 6.0 on 2026-01-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.ImageField(upload_to='user/'),
        ),
    ]
