# Generated by Django 6.0 on 2026-01-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
