# Generated by Django 6.0 on 2026-01-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('address', models.CharField(max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('price', models.PositiveIntegerField()),
                ('location_url', models.URLField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('rules', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(related_name='turfs', to='Turf.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(related_name='turfs', to='Turf.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TurfPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_hour_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekend_hour_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekday_full_day_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekend_full_day_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peak_start', models.TimeField()),
                ('peak_end', models.TimeField()),
                ('peak_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('turf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Turf.turf')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('full_day', 'Full Day')], max_length=10)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Turf.turf')),
            ],
            options={
                'indexes': [models.Index(fields=['turf', 'booking_date'], name='Turf_bookin_turf_id_a78a2f_idx')],
            },
        ),
    ]
