# Generated by Django 6.0 on 2026-01-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0002_remove_booking_price_booking_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
