POST http://127.0.0.1:8081/api/login/
Content-Type: application/json


{
  "email": "rohit@gmail.com",
    "password": "veni"
}

###
POST http://localhost:8081/api/bookings/validate/
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MTMzMTIwLCJpYXQiOjE3Njc1MjgzMjAsImp0aSI6ImJmZjZhMDEzZDg2NTQ5NWJhNTE0ZTZiNmNlZDQ0Mjc2IiwidXNlcl9pZCI6IjQiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6Im1hZ2VzaGFuQGdtYWlsLmNvbSJ9.aS4MnmkkYUTQISJkGuyuOxq5fOglnLUkVvAiAw5Nfbw

{
  "turf_id": 1,
  "selected_date": "2026-05-20",
  "selected_slots": [
    "13:00"
  ]
}



####
POST  http://localhost:8081/api/bookings/confirm/
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MTMzMTIwLCJpYXQiOjE3Njc1MjgzMjAsImp0aSI6ImJmZjZhMDEzZDg2NTQ5NWJhNTE0ZTZiNmNlZDQ0Mjc2IiwidXNlcl9pZCI6IjQiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6Im1hZ2VzaGFuQGdtYWlsLmNvbSJ9.aS4MnmkkYUTQISJkGuyuOxq5fOglnLUkVvAiAw5Nfbw

{
  "turf_details": {
    "turf_id": 1
  },
  "booking_details": {
    "date": "2026-05-20",
    "slots": [
      "3:00 PM",
      "4:00 PM"
    ]
  },
  "payment_details": {
    "payment_method": "google_pay",
    "transaction_id": "txn_123456789"
  }
}


###
GET  http://localhost:8081/api/turfs/bookings/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MTMzMTIwLCJpYXQiOjE3Njc1MjgzMjAsImp0aSI6ImJmZjZhMDEzZDg2NTQ5NWJhNTE0ZTZiNmNlZDQ0Mjc2IiwidXNlcl9pZCI6IjQiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6Im1hZ2VzaGFuQGdtYWlsLmNvbSJ9.aS4MnmkkYUTQISJkGuyuOxq5fOglnLUkVvAiAw5Nfbw

####
POST http://localhost:8081/api/bookings/pay/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MTMzMTIwLCJpYXQiOjE3Njc1MjgzMjAsImp0aSI6ImJmZjZhMDEzZDg2NTQ5NWJhNTE0ZTZiNmNlZDQ0Mjc2IiwidXNlcl9pZCI6IjQiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6Im1hZ2VzaGFuQGdtYWlsLmNvbSJ9.aS4MnmkkYUTQISJkGuyuOxq5fOglnLUkVvAiAw5Nfbw


{
  "turf_id": 1,
  "booking_details": {
    "date": "2026-01-10",
    "start_time": "3:00",
    "duration_hours": 1
  },
  "payment_info": {
    "method": "UPI",
    "transaction_ref": "TXN_UPI_778900"
  },
  "device_timestamp": "2026-05-20T18:05:00Z"
}



###
GET  http://localhost:8081/api/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MzAwMDMyLCJpYXQiOjE3Njc2OTUyMzIsImp0aSI6ImM2M2U3ZDI0NDVmNjQ3NWRhYzM4ZWJjZDk3MGIzZjEzIiwidXNlcl9pZCI6IjMiLCJyb2xlIjoiY3VzdG9tZXIiLCJlbWFpbCI6InJhbWFuYUBnbWFpbC5jb20ifQ.OQTxl7liQec74d_y7MYwIs0Zr9JSdXS6HjbPf-Wq2Zc

####
GET http://localhost:8081/api/slots?turf_id=1&date=2023-10-25
Content-Type: application/json



####
GET http://localhost:8081/api/admin/dashboard/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4MjA5NjMyLCJpYXQiOjE3Njc2MDQ4MzIsImp0aSI6IjRhYmIxNDBkMGY0YzRlNzQ4NjRkMTdiYWU2Y2U3MzYxIiwidXNlcl9pZCI6IjUiLCJyb2xlIjoiYnVzaW5lc3MiLCJlbWFpbCI6IlBvbnlAdHJ1Zi5jb20ifQ.cBJlPOIz3lOLcqEbXzDRvIn1kddJLKBne2sC5cyI3hk